---
apiVersion: v1
data:
    password: Vm13YXJlMTgj
kind: Secret
metadata:
    name: cart-redis-pass
---
apiVersion: v1
data:
    password: Vm13YXJlMTgj
kind: Secret
metadata:
    name: catalog-mongo-pass
---
apiVersion: v1
data:
    password: Vm13YXJlMTgj
kind: Secret
metadata:
    name: order-postgres-pass
---
apiVersion: v1
data:
  password: Vm13YXJlMTgj
kind: Secret
metadata:
  name: users-mongo-pass
---
apiVersion: v1
data:
    password: Vm13YXJlMTgj
kind: Secret
metadata:
    name: users-redis-pass