apiVersion: v1
kind: Service
metadata:
  labels:
    app: acmefit
    service: frontend
  name: frontend
spec:
  ports:
  - name: http-frontend
    nodePort: 30566
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: acmefit
    service: frontend
  type: NodePort
